-- Comprehensive Freshworks CRM Database Schema
-- This schema includes ALL fields from each module

-- 1. Deals table (with all fields)
CREATE TABLE IF NOT EXISTS deals (
  id BIGINT PRIMARY KEY,
  name TEXT,
  amount DECIMAL(15,2),
  base_currency_amount DECIMAL(15,2),
  expected_close_on DATE,
  closed_on DATE,
  stage_id BIGINT,
  probability INTEGER,
  deal_stage_id BIGINT,
  deal_reason_id BIGINT,
  deal_payment_status_id BIGINT,
  deal_product_id BIGINT,
  deal_type_id BIGINT,
  lead_source_id BIGINT,
  business_type_id BIGINT,
  campaign_id BIGINT,
  sales_account_id BIGINT,
  deal_pipeline_id BIGINT,
  currency_id BIGINT,
  owner_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  last_contacted_at TIMESTAMP WITH TIME ZONE,
  last_contacted_mode TEXT,
  last_contacted_sales_activity_mode TEXT,
  last_contacted_via_sales_activity BOOLEAN,
  expected_deal_value DECIMAL(15,2),
  is_deleted BOOLEAN DEFAULT false,
  team_user_ids BIGINT[],
  avatar TEXT,
  facebook TEXT,
  twitter TEXT,
  linkedin TEXT,
  contacts JSONB,
  products JSONB,
  organization JSONB,
  custom_fields JSONB,
  tags TEXT[],
  forecast_category INTEGER,
  deal_stage TEXT,
  age INTEGER,
  upcoming_activities_time TIMESTAMP WITH TIME ZONE,
  is_won BOOLEAN DEFAULT false,
  is_lost BOOLEAN DEFAULT false,
  recent_note TEXT,
  completed_sales_sequences TEXT,
  active_sales_sequences TEXT,
  web_form_id BIGINT,
  temperature TEXT,
  recent_sales_activity_id BIGINT,
  recent_sales_activity_type TEXT,
  recent_sales_activity_date TIMESTAMP WITH TIME ZONE,
  creater_id BIGINT,
  updater_id BIGINT,
  source_id BIGINT,
  territory_id BIGINT,
  deal_prediction INTEGER,
  deal_prediction_last_updated_at TIMESTAMP WITH TIME ZONE
);

-- 2. Contacts table (with all fields)
CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT PRIMARY KEY,
  first_name TEXT,
  last_name TEXT,
  display_name TEXT,
  avatar TEXT,
  job_title TEXT,
  city TEXT,
  state TEXT,
  zipcode TEXT,
  country TEXT,
  email TEXT,
  emails TEXT[],
  time_zone TEXT,
  work_number TEXT,
  mobile_number TEXT,
  address TEXT,
  last_seen TIMESTAMP WITH TIME ZONE,
  lead_score INTEGER,
  last_contacted TIMESTAMP WITH TIME ZONE,
  open_deals_amount DECIMAL(15,2),
  won_deals_amount DECIMAL(15,2),
  links JSONB,
  last_contacted_sales_activity_mode TEXT,
  custom_fields JSONB,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  keyword TEXT,
  medium TEXT,
  last_contacted_mode TEXT,
  recent_note TEXT,
  is_deleted BOOLEAN DEFAULT false,
  team_user_ids BIGINT[],
  lead_source_id BIGINT,
  owner_id BIGINT,
  territory_id BIGINT,
  campaign_id BIGINT,
  creater_id BIGINT,
  updater_id BIGINT,
  source_id BIGINT,
  life_cycle_stage_id BIGINT,
  contact_status_id BIGINT,
  sales_accounts JSONB,
  deals JSONB,
  tasks JSONB,
  appointments JSONB,
  notes JSONB,
  subscriptions JSONB,
  web_form_ids BIGINT[],
  open_activities_count INTEGER,
  unsubscription_status JSONB,
  email_status TEXT,
  last_contacted_via_chat TIMESTAMP WITH TIME ZONE,
  last_contacted_via_sales_activity TIMESTAMP WITH TIME ZONE,
  completed_sales_sequences TEXT,
  active_sales_sequences TEXT,
  last_assigned_at TIMESTAMP WITH TIME ZONE,
  tags TEXT[],
  facebook TEXT,
  twitter TEXT,
  linkedin TEXT,
  is_from_crm BOOLEAN DEFAULT true,
  contact_type TEXT,
  total_sessions INTEGER,
  system_tags TEXT[],
  first_campaign TEXT,
  first_medium TEXT,
  first_source TEXT,
  last_campaign TEXT,
  last_medium TEXT,
  last_source TEXT,
  latest_campaign TEXT,
  latest_medium TEXT,
  latest_source TEXT,
  mc_contact_status TEXT,
  first_mc_update_at TIMESTAMP WITH TIME ZONE,
  last_mc_update_at TIMESTAMP WITH TIME ZONE,
  first_seen TIMESTAMP WITH TIME ZONE,
  locale TEXT,
  time_to_contact INTEGER,
  department TEXT,
  designation TEXT
);

-- 3. Accounts/Companies table
CREATE TABLE IF NOT EXISTS accounts (
  id BIGINT PRIMARY KEY,
  name TEXT,
  address TEXT,
  city TEXT,
  state TEXT,
  zipcode TEXT,
  country TEXT,
  number_of_employees INTEGER,
  annual_revenue DECIMAL(15,2),
  website TEXT,
  phone TEXT,
  facebook TEXT,
  twitter TEXT,
  linkedin TEXT,
  industry_type_id BIGINT,
  business_type_id BIGINT,
  territory_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  avatar TEXT,
  custom_fields JSONB,
  open_deals_amount DECIMAL(15,2),
  won_deals_amount DECIMAL(15,2),
  open_deals_count INTEGER,
  won_deals_count INTEGER,
  last_contacted TIMESTAMP WITH TIME ZONE,
  last_contacted_mode TEXT,
  owner_id BIGINT,
  parent_sales_account_id BIGINT,
  recent_note TEXT,
  is_deleted BOOLEAN DEFAULT false,
  team_user_ids BIGINT[],
  creater_id BIGINT,
  updater_id BIGINT,
  source_id BIGINT,
  contacts JSONB,
  deals JSONB,
  tasks JSONB,
  appointments JSONB,
  notes JSONB,
  documents JSONB,
  tags TEXT[],
  is_primary BOOLEAN DEFAULT false,
  child_sales_account_ids BIGINT[],
  activities JSONB,
  remote_id TEXT,
  sync_status TEXT,
  last_synced_at TIMESTAMP WITH TIME ZONE
);

-- 4. Sales Activities table (with all fields)
CREATE TABLE IF NOT EXISTS sales_activities (
  id BIGINT PRIMARY KEY,
  title TEXT,
  notes TEXT,
  start_date TIMESTAMP WITH TIME ZONE,
  end_date TIMESTAMP WITH TIME ZONE,
  is_completed BOOLEAN DEFAULT false,
  targetable_type TEXT,
  targetable_id BIGINT,
  creater_id BIGINT,
  updater_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  owner_id BIGINT,
  checkedin_at TIMESTAMP WITH TIME ZONE,
  checkedout_at TIMESTAMP WITH TIME ZONE,
  approval_status INTEGER,
  outcome_id BIGINT,
  conversation_time INTEGER,
  location TEXT,
  latitude DECIMAL(10,8),
  longitude DECIMAL(11,8),
  checkedin_latitude DECIMAL(10,8),
  checkedin_longitude DECIMAL(11,8),
  checkedout_latitude DECIMAL(10,8),
  checkedout_longitude DECIMAL(11,8),
  associated_deal_ids BIGINT[],
  s_type TEXT,
  remote_id TEXT,
  import_id TEXT,
  meeting_id TEXT,
  note_id BIGINT,
  task_id BIGINT,
  event_id BIGINT,
  is_deleted BOOLEAN DEFAULT false,
  sync_status TEXT,
  activity_type TEXT,
  activity_sub_type TEXT,
  call_duration INTEGER,
  recording_url TEXT,
  email_cc TEXT[],
  email_bcc TEXT[],
  email_subject TEXT,
  email_body TEXT,
  email_attachments JSONB,
  sms_content TEXT,
  sms_status TEXT,
  chat_transcript TEXT,
  meeting_url TEXT,
  meeting_provider TEXT,
  meeting_recording_url TEXT,
  custom_fields JSONB,
  tags TEXT[],
  attendees JSONB,
  deal_ids BIGINT[],
  contact_ids BIGINT[],
  sales_account_ids BIGINT[]
);

-- 5. Appointments table (already comprehensive from discovery)
CREATE TABLE IF NOT EXISTS appointments (
  id BIGINT PRIMARY KEY,
  title TEXT,
  description TEXT,
  location TEXT,
  from_date TIMESTAMP WITH TIME ZONE,
  end_date TIMESTAMP WITH TIME ZONE,
  is_allday BOOLEAN DEFAULT false,
  time_zone TEXT,
  provider TEXT,
  creater_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  outcome_id BIGINT,
  latitude DECIMAL(10,8),
  longitude DECIMAL(11,8),
  checkedin_at TIMESTAMP WITH TIME ZONE,
  can_checkin_checkout BOOLEAN DEFAULT true,
  checkedout_latitude DECIMAL(10,8),
  checkedout_longitude DECIMAL(11,8),
  checkedout_location TEXT,
  checkedout_at TIMESTAMP WITH TIME ZONE,
  checkedin_duration INTEGER,
  can_checkin BOOLEAN DEFAULT true,
  conference_id TEXT,
  targetables JSONB,
  targetables_with_email JSONB,
  has_multiple_emails BOOLEAN DEFAULT false,
  appointment_attendees JSONB,
  is_recurring BOOLEAN DEFAULT false,
  recurring_pattern TEXT,
  recurring_end_date DATE,
  parent_appointment_id BIGINT,
  is_private BOOLEAN DEFAULT false,
  reminder_time INTEGER,
  color_code TEXT,
  google_event_id TEXT,
  outlook_event_id TEXT,
  sync_status TEXT,
  last_synced_at TIMESTAMP WITH TIME ZONE,
  owner_id BIGINT,
  deal_ids BIGINT[],
  contact_ids BIGINT[],
  account_ids BIGINT[],
  custom_fields JSONB,
  tags TEXT[]
);

-- 6. Tasks table
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT PRIMARY KEY,
  title TEXT,
  description TEXT,
  due_date TIMESTAMP WITH TIME ZONE,
  task_type_id BIGINT,
  owner_id BIGINT,
  creater_id BIGINT,
  updater_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  status INTEGER,
  priority INTEGER,
  outcome_id BIGINT,
  is_completed BOOLEAN DEFAULT false,
  completed_date TIMESTAMP WITH TIME ZONE,
  targetable_type TEXT,
  targetable_id BIGINT,
  taskable_type TEXT,
  taskable_id BIGINT,
  position INTEGER,
  checklist_id BIGINT,
  checklist_template_id BIGINT,
  is_deleted BOOLEAN DEFAULT false,
  team_user_ids BIGINT[],
  reminder_time TIMESTAMP WITH TIME ZONE,
  custom_fields JSONB,
  tags TEXT[],
  associated_deal_ids BIGINT[],
  associated_contact_ids BIGINT[],
  associated_account_ids BIGINT[],
  notes TEXT,
  remote_id TEXT,
  sync_status TEXT,
  last_synced_at TIMESTAMP WITH TIME ZONE,
  is_recurring BOOLEAN DEFAULT false,
  recurring_pattern TEXT,
  parent_task_id BIGINT,
  subtasks JSONB,
  attachments JSONB,
  followers BIGINT[],
  time_spent INTEGER,
  estimated_time INTEGER
);

-- 7. Products table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT PRIMARY KEY,
  name TEXT,
  description TEXT,
  sku_number TEXT,
  active BOOLEAN DEFAULT true,
  deleted BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  parent_product_id BIGINT,
  currency_id BIGINT,
  product_code TEXT,
  is_service BOOLEAN DEFAULT false,
  unit_price DECIMAL(15,2),
  cost DECIMAL(15,2),
  tax_rate DECIMAL(5,2),
  mrr DECIMAL(15,2),
  billing_cycle INTEGER,
  billing_type TEXT,
  quantity_in_stock INTEGER,
  valid_till DATE,
  avatar TEXT,
  product_category_id BIGINT,
  vendor_id BIGINT,
  owner_id BIGINT,
  creater_id BIGINT,
  updater_id BIGINT,
  custom_fields JSONB,
  tags TEXT[],
  commission_rate DECIMAL(5,2),
  is_commission_applicable BOOLEAN DEFAULT false,
  unit_of_measurement TEXT,
  tax_treatment TEXT,
  product_family_id BIGINT,
  require_shipping BOOLEAN DEFAULT false,
  weight DECIMAL(10,2),
  dimensions TEXT,
  manufacturer TEXT,
  brand TEXT,
  attachments JSONB,
  pricing_tiers JSONB,
  discounts JSONB,
  related_products BIGINT[],
  product_options JSONB,
  is_recurring BOOLEAN DEFAULT false,
  recurring_price DECIMAL(15,2),
  trial_period INTEGER
);

-- 8. Leads table
CREATE TABLE IF NOT EXISTS leads (
  id BIGINT PRIMARY KEY,
  first_name TEXT,
  last_name TEXT,
  email TEXT,
  work_number TEXT,
  mobile_number TEXT,
  address TEXT,
  city TEXT,
  state TEXT,
  zipcode TEXT,
  country TEXT,
  time_zone TEXT,
  company_name TEXT,
  website TEXT,
  job_title TEXT,
  lead_source_id BIGINT,
  lead_status_id BIGINT,
  lead_reason_id BIGINT,
  owner_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  last_contacted TIMESTAMP WITH TIME ZONE,
  last_contacted_mode TEXT,
  lead_score INTEGER,
  lead_quality INTEGER,
  stage TEXT,
  converted BOOLEAN DEFAULT false,
  converted_at TIMESTAMP WITH TIME ZONE,
  converted_contact_id BIGINT,
  converted_account_id BIGINT,
  converted_deal_id BIGINT,
  junk_reason TEXT,
  is_junk BOOLEAN DEFAULT false,
  is_deleted BOOLEAN DEFAULT false,
  campaign_id BIGINT,
  medium TEXT,
  keyword TEXT,
  creater_id BIGINT,
  updater_id BIGINT,
  source_id BIGINT,
  custom_fields JSONB,
  tags TEXT[],
  facebook TEXT,
  twitter TEXT,
  linkedin TEXT,
  avatar TEXT,
  do_not_disturb BOOLEAN DEFAULT false,
  last_seen TIMESTAMP WITH TIME ZONE,
  first_seen TIMESTAMP WITH TIME ZONE,
  subscription_status TEXT,
  subscription_types TEXT[],
  unsubscription_reason TEXT,
  other_unsubscription_reason TEXT,
  customer_fit INTEGER,
  cf_decimal DECIMAL(15,2),
  territory_id BIGINT,
  currency_id BIGINT,
  expected_deal_value DECIMAL(15,2),
  industry_type_id BIGINT,
  business_type_id BIGINT,
  number_of_employees INTEGER,
  annual_revenue DECIMAL(15,2),
  recent_note TEXT,
  recent_campaign TEXT
);

-- 9. Notes table
CREATE TABLE IF NOT EXISTS notes (
  id BIGINT PRIMARY KEY,
  content TEXT,
  targetable_type TEXT,
  targetable_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  creater_id BIGINT,
  updater_id BIGINT,
  is_deleted BOOLEAN DEFAULT false,
  is_private BOOLEAN DEFAULT false,
  attachments JSONB,
  mentioned_users BIGINT[],
  tags TEXT[],
  associated_deal_ids BIGINT[],
  associated_contact_ids BIGINT[],
  associated_account_ids BIGINT[],
  note_type TEXT,
  remote_id TEXT,
  sync_status TEXT,
  last_synced_at TIMESTAMP WITH TIME ZONE
);

-- 10. Sales Team table (existing)
CREATE TABLE IF NOT EXISTS sales_team (
  id BIGINT PRIMARY KEY,
  display_name TEXT,
  email TEXT,
  is_active BOOLEAN DEFAULT false,
  work_number TEXT,
  mobile_number TEXT,
  job_title TEXT,
  team_id BIGINT,
  role_id BIGINT,
  reporting_to BIGINT,
  time_zone TEXT,
  date_format TEXT,
  language TEXT,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  last_login_at TIMESTAMP WITH TIME ZONE,
  avatar TEXT,
  signature TEXT,
  user_type TEXT,
  status TEXT,
  custom_fields JSONB,
  sales_targets JSONB,
  territories BIGINT[],
  skills TEXT[],
  certifications TEXT[]
);

-- 11. Contact Statuses/Pipeline Stages table (existing)
CREATE TABLE IF NOT EXISTS contact_statuses (
  id BIGINT PRIMARY KEY,
  name TEXT,
  position INTEGER,
  partial BOOLEAN DEFAULT false,
  forecast_type TEXT,
  lifecycle_stage_id BIGINT,
  probability INTEGER,
  velocity_days INTEGER,
  is_active BOOLEAN DEFAULT true,
  is_default BOOLEAN DEFAULT false,
  is_won BOOLEAN DEFAULT false,
  is_lost BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  color_code TEXT,
  deal_pipeline_id BIGINT,
  rotting_days INTEGER,
  stage_category TEXT
);

-- 12. Deal Pipelines table
CREATE TABLE IF NOT EXISTS deal_pipelines (
  id BIGINT PRIMARY KEY,
  name TEXT,
  is_active BOOLEAN DEFAULT true,
  is_default BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  stages JSONB,
  win_probability_by_stage JSONB,
  average_deal_size DECIMAL(15,2),
  average_deal_cycle INTEGER
);

-- 13. Email Templates table
CREATE TABLE IF NOT EXISTS email_templates (
  id BIGINT PRIMARY KEY,
  name TEXT,
  subject TEXT,
  body_html TEXT,
  body_text TEXT,
  folder_id BIGINT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  creater_id BIGINT,
  updater_id BIGINT,
  category TEXT,
  tags TEXT[],
  attachments JSONB,
  merge_fields JSONB,
  usage_count INTEGER DEFAULT 0,
  last_used_at TIMESTAMP WITH TIME ZONE
);

-- 14. Campaigns table
CREATE TABLE IF NOT EXISTS campaigns (
  id BIGINT PRIMARY KEY,
  name TEXT,
  description TEXT,
  start_date DATE,
  end_date DATE,
  budget DECIMAL(15,2),
  actual_cost DECIMAL(15,2),
  expected_revenue DECIMAL(15,2),
  campaign_type TEXT,
  campaign_status TEXT,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  owner_id BIGINT,
  parent_campaign_id BIGINT,
  custom_fields JSONB,
  tags TEXT[],
  target_audience TEXT,
  success_metrics JSONB,
  channels TEXT[],
  roi DECIMAL(10,2),
  conversion_rate DECIMAL(5,2),
  leads_generated INTEGER,
  deals_influenced INTEGER,
  revenue_influenced DECIMAL(15,2)
);

-- Create indexes for better query performance
CREATE INDEX idx_deals_owner_id ON deals(owner_id);
CREATE INDEX idx_deals_stage_id ON deals(stage_id);
CREATE INDEX idx_deals_expected_close ON deals(expected_close_on);
CREATE INDEX idx_deals_amount ON deals(amount);
CREATE INDEX idx_deals_is_won ON deals(is_won);
CREATE INDEX idx_deals_is_lost ON deals(is_lost);

CREATE INDEX idx_contacts_owner_id ON contacts(owner_id);
CREATE INDEX idx_contacts_email ON contacts(email);
CREATE INDEX idx_contacts_life_cycle_stage ON contacts(life_cycle_stage_id);

CREATE INDEX idx_accounts_owner_id ON accounts(owner_id);
CREATE INDEX idx_accounts_name ON accounts(name);

CREATE INDEX idx_sales_activities_targetable ON sales_activities(targetable_type, targetable_id);
CREATE INDEX idx_sales_activities_owner_id ON sales_activities(owner_id);
CREATE INDEX idx_sales_activities_start_date ON sales_activities(start_date);

CREATE INDEX idx_appointments_from_date ON appointments(from_date);
CREATE INDEX idx_appointments_creater_id ON appointments(creater_id);

CREATE INDEX idx_tasks_due_date ON tasks(due_date);
CREATE INDEX idx_tasks_owner_id ON tasks(owner_id);
CREATE INDEX idx_tasks_status ON tasks(status);

CREATE INDEX idx_leads_owner_id ON leads(owner_id);
CREATE INDEX idx_leads_converted ON leads(converted);
CREATE INDEX idx_leads_lead_status ON leads(lead_status_id); 