version: '3'
services:
  tooljet:
    image: tooljet/tooljet-ce:latest
    ports:
      - '8080:3000'
    environment:
      - TOOLJET_HOST=http://localhost:8080
      - PG_HOST=postgres
      - PG_DB=tooljet_app
      - PG_USER=postgres
      - PG_PASS=tooljet
      - TOOLJET_DB_HOST=postgres
      - TOOLJET_DB=tooljet_db
      - TOOLJET_DB_USER=postgres
      - TOOLJET_DB_PASS=tooljet
      - SECRET_KEY_BASE=replace_with_secret_key_base
      - LOCKBOX_MASTER_KEY=replace_with_lockbox_master_key
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tooljet_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tooljet
volumes:
  postgres_data: 