version: '3'
services:
  tooljet:
    image: tooljet/tooljet-ce:latest
    ports:
      - '9090:3000'
    environment:
      - TOOLJET_HOST=http://localhost:9090
      - PG_HOST=postgres
      - PG_DB=tooljet_prod
      - PG_USER=postgres
      - PG_PASS=tooljet
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tooljet_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tooljet
volumes:
  postgres_data: 